# Generated by Django 5.2.8 on 2025-11-23 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('size', models.FloatField(help_text='Size in hectares')),
                ('crop_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_variety', models.CharField(max_length=100)),
                ('size', models.FloatField(help_text='Size in hectares')),
                ('location_coordinates', models.CharField(blank=True, max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='farms.farmprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('moisture', 'Soil Moisture'), ('temperature', 'Air Temperature'), ('humidity', 'Humidity')], max_length=20)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='simulator', max_length=50)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='farms.fieldplot')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
