# Generated by Django 5.2.8 on 2025-11-23 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('moisture_drop', 'Moisture Drop'), ('temperature_high', 'High Temperature'), ('humidity_low', 'Low Humidity'), ('sensor_drift', 'Sensor Drift')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('model_confidence', models.FloatField(help_text='Confidence score from ML model')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='farms.fieldplot')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_action', models.CharField(max_length=200)),
                ('explanation_text', models.TextField()),
                ('confidence', models.CharField(max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='farms.anomalyevent')),
            ],
        ),
    ]
